# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '10.x'

      - name: Ci
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Running npm tests
        run: npm test -- --watch=false --progress=false
        env:
          CI: true
